#!/usr/bin/env bash
cp -av /autograder/submission/ece0301_ICA*.cpp /autograder/source/submissions

cd /autograder/source
mkdir submissions
mkdir test_dir


python3 run_tests.py > /autograder/results/results.json


