all:step18
step18: ece0301_ICA13_step18.cpp Lhdeccic.cpp Signal.cpp Folhdeccic.cpp Solhdeccic.cpp
	g++ ece0301_ICA13_step18.cpp Lhdeccic.cpp Signal.cpp Folhdeccic.cpp Solhdeccic.cpp -o ece0301_ICA13_step18.exe

.PHONY: clean

clean:
	rm -f  *.exe *.o *.gch


