all:step16
step16: ece0301_ICA13_step16.cpp Lhdeccic.cpp Signal.cpp Folhdeccic.cpp Solhdeccic.cpp
	g++ ece0301_ICA13_step16.cpp Lhdeccic.cpp Signal.cpp Folhdeccic.cpp Solhdeccic.cpp -o ece0301_ICA13_step16.exe

.PHONY: clean

clean:
	rm -f  *.exe *.o *.gch


