all:step08
step08: ece0301_ICA13_step08.cpp Lhdeccic.cpp Signal.cpp Folhdeccic.cpp
	g++ ece0301_ICA13_step08.cpp Lhdeccic.cpp Signal.cpp Folhdeccic.cpp -o ece0301_ICA13_step08.exe

.PHONY: clean

clean:
	rm -f  *.exe *.o *.gch


