all:step07
step07: ece0301_ICA13_step07.cpp Lhdeccic.cpp Signal.cpp Folhdeccic.cpp
	g++ ece0301_ICA13_step07.cpp Lhdeccic.cpp Signal.cpp Folhdeccic.cpp -o ece0301_ICA13_step07.exe

.PHONY: clean

clean:
	rm -f  *.exe *.o *.gch


