all:step13
step13: ece0301_ICA13_step13.cpp Lhdeccic.cpp Signal.cpp Folhdeccic.cpp Solhdeccic.cpp
	g++ ece0301_ICA13_step13.cpp Lhdeccic.cpp Signal.cpp Folhdeccic.cpp Solhdeccic.cpp -o ece0301_ICA13_step13.exe

.PHONY: clean

clean:
	rm -f  *.exe *.o *.gch


